### inicio app 

###  Home Search
GET http://localhost:8000/movies/search?&page=1&limit=10&sortByDate=-1
Content-Type: application/json

### Search by Title + sort by rating 
GET http://localhost:8000/movies/search?&name=godzilla&page=1&limit=10&sortByRating=1
Content-Type: application/json

### Search by Actor
GET http://localhost:8000/movies/search?&name=ryan%20reynolds&page=1&limit=10&sortByDate=-1
Content-Type: application/json

### Search by Genre
GET http://localhost:8000/movies/search?&genre=adventure&page=1&limit=10&sortByRating=1
Content-Type: application/json

### movies rate 
//agregar el dato por body userId
PUT http://localhost:8000/movies/rating/660c8a9aefbf168167216717
Content-Type: application/json

{
    "userId": "5",
    "rate": 5
}

